### ISSUE TITLE
Calendar not showing open issues in mega_calendar widget Redmine 3.3.0

### ISSUE THREAD

**Issue by jlibster** [berti92/mega_calendar#56]
The mega_calendar is not showing ANY issues at all if there is not start/due date. A fork seems to be okay even without these fields. The Calendar should show the issues with option of using creation date if there is not start/due date so it shows up like it does on the issues interface or it's confusing.

Update:Have to allow the Start Date and Due date to show up on the main redhat default Calendar, but it doesn't seems to show up on the megacalendar when I put it put up on "My Page". So any idea how to get my issues with start and due dates to show with the megacalendar widget I can place on "my page"?  The global mega_calendar seems to be okay.

An additional feature would be to have a "global" scope holiday as well as holiday titles (for example, Martin Luther King Jr, Day, or Christmas, or "Family Day" (in Canada) . That would make the holiday portion of this plugin more commercial ready. :-)

**Comment by berti92** [comment]
Hi,

thank you for your feedback.

I currently work on a another bigger release which includes global holidays.
For documentation: It should be no problem if a start OR due date is given, if both of them are missing then the issue is not displayed.
The problem with the missing start AND due date is a valid point, so I add this as an enhancement with config

Best regards

**Comment by berti92** [comment]
Done within V1.6.0
